exp: 
  backbone: mit_b5

dataset:
  root_dir: /workspace/dataset/cityscapes/
  name_list_dir: datasets/voc
  num_classes: 19
  crop_size: 768
  resize_range: [1024, 2048]
  rescale_range: [0.5, 2.0]
  ignore_index: 255

train:
  split: train_aug
  samples_per_gpu: 8
  max_iters: 160000
  eval_iters: 8000
  log_iters: 50

val:
  split: val

optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 1500
  warmup_ratio: 1e-6
  power: 1.0