exp: 
  backbone: mit_b5

dataset:
  root_dir: /home/rlx/VOCdevkit/VOC2012
  name_list_dir: datasets/voc
  num_classes: 21
  crop_size: 512
  resize_range: [512, 2048]
  rescale_range: [0.5, 2.0]
  ignore_index: 255

train:
  split: train_aug
  samples_per_gpu: 3
  max_iters: 40000
  eval_iters: 5000
  log_iters: 50

val:
  split: val

optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 1500
  warmup_ratio: 1e-6
  power: 1.0